name: environment_ML_Project
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - pip:
    - ipykernel
    - numpy
    - scikit-learn
    - matplotlib
    - optuna
    - lightgbm
    - librosa
    - pandas
    - pysoundfile
    - regex